version: '3.9'

services:
  bubberstation-gameserver:
    build: .
    container_name: bubber-codebasefun
    tty: true
    environment:
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - ./:/home/tgstation-server
    ports:
      - "1337:1337"
    command: /bin/bash

  mariadb-bubberstation:
    image: mariadb:latest
    container_name: mariadb-bubberstation
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "5001:3306"
    volumes:
      - ./sql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password